import { Category, Product, Coupon, Address, Order } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-fruits-veg",
    slug: "fruits-vegetables",
    name: "Fruits & Vegetables",
    description: "Farm fresh organic fruits and crisp vegetables handpicked daily",
    icon: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&auto=format&fit=crop&q=80",
    sortOrder: 1,
    itemCount: 42,
  },
  {
    id: "cat-dairy-breakfast",
    slug: "dairy-breakfast",
    name: "Dairy & Breakfast",
    description: "Pure milk, farm eggs, artisanal cheeses, butter & morning yogurt",
    icon: "Milk",
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80",
    sortOrder: 2,
    itemCount: 36,
  },
  {
    id: "cat-bakery",
    slug: "bakery",
    name: "Bakery & Breads",
    description: "Oven-baked sourdough, croissants, bagels, and artisan cookies",
    icon: "Croissant",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80",
    sortOrder: 3,
    itemCount: 28,
  },
  {
    id: "cat-beverages",
    slug: "beverages",
    name: "Beverages & Juices",
    description: "Cold-pressed juices, sparkling waters, organic teas, and roasts",
    icon: "Coffee",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80",
    sortOrder: 4,
    itemCount: 31,
  },
  {
    id: "cat-snacks",
    slug: "snacks",
    name: "Snacks & Munchies",
    description: "Gourmet chips, roasted nuts, dried fruits, dips, and dark chocolate",
    icon: "Cookie",
    imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop&q=80",
    sortOrder: 5,
    itemCount: 45,
  },
  {
    id: "cat-meat-seafood",
    slug: "meat-seafood",
    name: "Meat & Seafood",
    description: "Responsibly sourced salmon fillets, pasture-raised chicken, and prime cuts",
    icon: "Fish",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80",
    sortOrder: 6,
    itemCount: 22,
  },
  {
    id: "cat-staples",
    slug: "staples-cooking",
    name: "Staples & Pantry",
    description: "Extra virgin olive oils, Himalayan grains, pasta, pulses, and spices",
    icon: "Wheat",
    imageUrl: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80",
    sortOrder: 7,
    itemCount: 54,
  },
  {
    id: "cat-household",
    slug: "household-personal",
    name: "Household & Personal Care",
    description: "Eco-friendly cleaners, organic bamboo paper, and gentle skincare",
    icon: "Sparkles",
    imageUrl: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&auto=format&fit=crop&q=80",
    sortOrder: 8,
    itemCount: 39,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  // Fruits & Veg
  {
    id: "prod-1",
    slug: "organic-hass-avocados",
    name: "Organic Hass Avocados",
    brand: "Earth Organics",
    categoryId: "cat-fruits-veg",
    categoryName: "Fruits & Vegetables",
    description: "Creamy, nutrient-rich Haas avocados hand-selected at peak maturity. Perfect for toasts, salads, or fresh guacamole.",
    specifications: {
      "Origin": "California, USA",
      "Ripeness": "Ready to eat within 2-3 days",
      "Storage": "Store at room temp until ripe, then refrigerate",
      "Dietary": "100% Organic, Non-GMO, Vegan",
    },
    price: 4.49,
    originalPrice: 5.99,
    discountPercent: 25,
    unit: "Pack of 4",
    stock: 85,
    rating: 4.8,
    ratingCount: 312,
    images: [
      "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1601039641847-7857b994d704?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    isFeatured: true,
    isDeal: true,
    tags: ["organic", "fresh", "bestseller", "healthy"],
    inStock: true,
  },
  {
    id: "prod-2",
    slug: "sweet-fresh-strawberries",
    name: "Sweet Driscoll's Strawberries",
    brand: "Driscoll's",
    categoryId: "cat-fruits-veg",
    categoryName: "Fruits & Vegetables",
    description: "Plump, ruby-red strawberries bursting with natural sweetness and aromatic flavor. Handpicked and cooled within hours of harvest.",
    specifications: {
      "Net Weight": "1 lb (454g)",
      "Origin": "Watsonville, CA",
      "Storage": "Keep refrigerated at 34°-38°F",
      "Quality": "Grade A Super Sweet",
    },
    price: 3.99,
    originalPrice: 4.99,
    discountPercent: 20,
    unit: "1 lb clamshell",
    stock: 45,
    rating: 4.7,
    ratingCount: 198,
    images: [
      "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1543528176-61b239494933?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    isFeatured: true,
    tags: ["berry", "sweet", "vitamin-c"],
    inStock: true,
  },
  {
    id: "prod-3",
    slug: "organic-baby-spinach",
    name: "Organic Tender Baby Spinach",
    brand: "Earthbound Farm",
    categoryId: "cat-fruits-veg",
    categoryName: "Fruits & Vegetables",
    description: "Triple-washed tender baby spinach leaves. Mild, buttery flavor that sautés quickly or acts as the ideal salad foundation.",
    specifications: {
      "Net Weight": "16 oz (454g)",
      "Certification": "USDA Organic",
      "Preparation": "Triple Washed & Ready to Eat",
    },
    price: 3.29,
    originalPrice: 3.99,
    discountPercent: 18,
    unit: "16 oz container",
    stock: 60,
    rating: 4.9,
    ratingCount: 245,
    images: [
      "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    tags: ["greens", "salad", "iron-rich"],
    inStock: true,
  },
  {
    id: "prod-4",
    slug: "organic-bananas-bunch",
    name: "Organic Fair Trade Bananas",
    brand: "Equifruit",
    categoryId: "cat-fruits-veg",
    categoryName: "Fruits & Vegetables",
    description: "Naturally ripened, sweet bananas certified organic and fair trade. High in potassium and energy.",
    specifications: {
      "Weight": "Approx. 2.5 lbs (5-7 bananas)",
      "Source": "Ecuador Fair Trade Co-op",
    },
    price: 1.89,
    originalPrice: 2.29,
    discountPercent: 17,
    unit: "1 Bunch (~2.5 lbs)",
    stock: 120,
    rating: 4.6,
    ratingCount: 512,
    images: [
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    tags: ["fruit", "potassium", "staple"],
    inStock: true,
  },

  // Dairy & Breakfast
  {
    id: "prod-5",
    slug: "organic-whole-milk-half-gallon",
    name: "Organic Grass-Fed Whole Milk",
    brand: "Horizon Organic",
    categoryId: "cat-dairy-breakfast",
    categoryName: "Dairy & Breakfast",
    description: "Creamy, delicious whole milk from pasture-raised cows never treated with antibiotics or synthetic hormones.",
    specifications: {
      "Volume": "64 fl oz (1/2 Gallon)",
      "Fat Content": "3.25% Milkfat",
      "Packaging": "Recyclable carton with twist cap",
    },
    price: 4.89,
    originalPrice: 5.49,
    discountPercent: 11,
    unit: "64 fl oz",
    stock: 70,
    rating: 4.9,
    ratingCount: 420,
    images: [
      "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    isFeatured: true,
    tags: ["dairy", "organic", "calcium"],
    inStock: true,
  },
  {
    id: "prod-6",
    slug: "pasture-raised-large-brown-eggs",
    name: "Pasture-Raised Large Brown Eggs",
    brand: "Vital Farms",
    categoryId: "cat-dairy-breakfast",
    categoryName: "Dairy & Breakfast",
    description: "Rich amber yolks from hens given 108 sq. ft. of outdoor pasture each. Ethically raised and packed with omega-3s.",
    specifications: {
      "Count": "12 Large Grade A Eggs",
      "Feed": "Pasture-foraged & Non-GMO grain",
      "Certification": "Certified Humane Pasture-Raised",
    },
    price: 5.99,
    originalPrice: 7.29,
    discountPercent: 18,
    unit: "1 Dozen",
    stock: 52,
    rating: 5.0,
    ratingCount: 680,
    images: [
      "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    isFeatured: true,
    isDeal: true,
    tags: ["eggs", "pasture-raised", "protein"],
    inStock: true,
  },
  {
    id: "prod-7",
    slug: "greek-strained-plain-yogurt",
    name: "Authentic Greek Strained Yogurt",
    brand: "FAGE Total",
    categoryId: "cat-dairy-breakfast",
    categoryName: "Dairy & Breakfast",
    description: "Thick, creamy 5% milkfat strained Greek yogurt with 18g protein per serving and no added sugars.",
    specifications: {
      "Net Weight": "32 oz (907g)",
      "Live Cultures": "5 Live & Active Probiotic Cultures",
      "Gluten-Free": "Yes",
    },
    price: 5.49,
    originalPrice: 6.29,
    discountPercent: 13,
    unit: "32 oz tub",
    stock: 38,
    rating: 4.8,
    ratingCount: 164,
    images: [
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&auto=format&fit=crop&q=80",
    ],
    tags: ["probiotics", "high-protein", "greek-yogurt"],
    inStock: true,
  },

  // Bakery & Breads
  {
    id: "prod-8",
    slug: "artisan-san-francisco-sourdough",
    name: "Artisan Country Sourdough Loaf",
    brand: "Bakehouse 1888",
    categoryId: "cat-bakery",
    categoryName: "Bakery & Breads",
    description: "Naturally fermented for 36 hours using a wild starter. Crisp caramelized crust with a soft, airy open crumb.",
    specifications: {
      "Weight": "24 oz (680g)",
      "Ingredients": "Organic flour, water, sea salt, wild levain",
      "Freshness": "Baked fresh every dawn",
    },
    price: 4.99,
    originalPrice: 6.50,
    discountPercent: 23,
    unit: "1 Loaf (24 oz)",
    stock: 25,
    rating: 4.9,
    ratingCount: 189,
    images: [
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    isFeatured: true,
    isDeal: true,
    tags: ["sourdough", "artisan", "fresh-baked"],
    inStock: true,
  },
  {
    id: "prod-9",
    slug: "french-butter-croissants",
    name: "All-Butter French Croissants",
    brand: "La Boulangerie",
    categoryId: "cat-bakery",
    categoryName: "Bakery & Breads",
    description: "Layered with European cultured butter for golden, flaky exterior and honeycomb interior.",
    specifications: {
      "Quantity": "4 Pack",
      "Butter Type": "82% European Style",
    },
    price: 5.29,
    originalPrice: 6.29,
    discountPercent: 16,
    unit: "Pack of 4",
    stock: 30,
    rating: 4.7,
    ratingCount: 142,
    images: [
      "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&auto=format&fit=crop&q=80",
    ],
    tags: ["croissant", "french", "breakfast"],
    inStock: true,
  },

  // Beverages
  {
    id: "prod-10",
    slug: "cold-pressed-orange-juice",
    name: "Cold-Pressed Valencia Orange Juice",
    brand: "SunGrove",
    categoryId: "cat-beverages",
    categoryName: "Beverages & Juices",
    description: "100% pure cold-pressed Valencia oranges. Never pasteurized with heat, preserving vibrant flavor and full enzymes.",
    specifications: {
      "Volume": "33.8 fl oz (1L)",
      "Added Sugars": "0g",
      "Process": "High Pressure Processing (HPP)",
    },
    price: 4.99,
    originalPrice: 6.29,
    discountPercent: 21,
    unit: "1 Liter Bottle",
    stock: 40,
    rating: 4.8,
    ratingCount: 220,
    images: [
      "https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    isDeal: true,
    tags: ["orange-juice", "cold-pressed", "refreshing"],
    inStock: true,
  },
  {
    id: "prod-11",
    slug: "organic-sparkling-spring-water",
    name: "Lime Sparkling Mineral Water",
    brand: "Spindrift",
    categoryId: "cat-beverages",
    categoryName: "Beverages & Juices",
    description: "Sparkling water squeezed with real fruit juice. Light, crisp, zero artificial flavors or sweeteners.",
    specifications: {
      "Pack": "8 x 12 fl oz cans",
      "Calories": "5 calories per can",
    },
    price: 6.49,
    originalPrice: 7.99,
    discountPercent: 19,
    unit: "Pack of 8 cans",
    stock: 55,
    rating: 4.7,
    ratingCount: 110,
    images: [
      "https://images.unsplash.com/photo-1556881286-fc6915169721?w=800&auto=format&fit=crop&q=80",
    ],
    tags: ["sparkling-water", "zero-sugar", "lime"],
    inStock: true,
  },

  // Snacks & Munchies
  {
    id: "prod-12",
    slug: "avocado-oil-kettle-chips",
    name: "Avocado Oil Sea Salt Kettle Chips",
    brand: "Boulder Canyon",
    categoryId: "cat-snacks",
    categoryName: "Snacks & Munchies",
    description: "Small-batch kettle chips cooked in 100% pure avocado oil and dusted with pure sea salt for extraordinary crunch.",
    specifications: {
      "Net Weight": "6.5 oz (184g)",
      "Oil": "100% Pure Avocado Oil",
      "Non-GMO": "Non-GMO Project Verified",
    },
    price: 3.49,
    originalPrice: 4.49,
    discountPercent: 22,
    unit: "6.5 oz bag",
    stock: 80,
    rating: 4.8,
    ratingCount: 310,
    images: [
      "https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    tags: ["chips", "kettle", "avocado-oil", "crunchy"],
    inStock: true,
  },
  {
    id: "prod-13",
    slug: "roasted-almonds-sea-salt",
    name: "Dry-Roasted California Almonds",
    brand: "Blue Diamond",
    categoryId: "cat-snacks",
    categoryName: "Snacks & Munchies",
    description: "Gently roasted in small batches with fine sea salt. Packed with magnesium, fiber, and clean protein.",
    specifications: {
      "Net Weight": "16 oz (1 lb)",
      "Salt": "Mediterranean Sea Salt",
    },
    price: 7.99,
    originalPrice: 9.99,
    discountPercent: 20,
    unit: "16 oz bag",
    stock: 65,
    rating: 4.9,
    ratingCount: 195,
    images: [
      "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    tags: ["nuts", "almonds", "healthy-snack"],
    inStock: true,
  },

  // Meat & Seafood
  {
    id: "prod-14",
    slug: "wild-caught-sockeye-salmon",
    name: "Wild Alaskan Sockeye Salmon Fillet",
    brand: "Ocean Harvest",
    categoryId: "cat-meat-seafood",
    categoryName: "Meat & Seafood",
    description: "Sustainably harvested in Bristol Bay, Alaska. Deep scarlet flesh with high levels of heart-healthy omega-3 EPA/DHA.",
    specifications: {
      "Net Weight": "1 lb (16 oz)",
      "Catch Method": "Hook & Line, MSC Certified",
      "Condition": "Skin-on, pin-bones removed",
    },
    price: 13.99,
    originalPrice: 16.99,
    discountPercent: 18,
    unit: "1 lb fillet",
    stock: 28,
    rating: 4.9,
    ratingCount: 156,
    images: [
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    isFeatured: true,
    tags: ["salmon", "wild-caught", "seafood", "omega-3"],
    inStock: true,
  },
  {
    id: "prod-15",
    slug: "organic-boneless-chicken-breast",
    name: "Air-Chilled Organic Chicken Breast",
    brand: "Smart Chicken",
    categoryId: "cat-meat-seafood",
    categoryName: "Meat & Seafood",
    description: "Pure air-chilled organic boneless skinless chicken breasts. No added water, superior texture and juicy natural flavor.",
    specifications: {
      "Net Weight": "Approx 1.25 lbs (2-3 fillets)",
      "Diet": "100% Organic Vegetarian Feed",
      "Chilling": "100% Pure Air Chilled",
    },
    price: 8.99,
    originalPrice: 10.49,
    discountPercent: 14,
    unit: "~1.25 lbs tray",
    stock: 35,
    rating: 4.8,
    ratingCount: 230,
    images: [
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800&auto=format&fit=crop&q=80",
    ],
    tags: ["chicken", "organic", "high-protein", "lean"],
    inStock: true,
  },

  // Staples & Pantry
  {
    id: "prod-16",
    slug: "extra-virgin-olive-oil-cold-extracted",
    name: "Single-Estate Extra Virgin Olive Oil",
    brand: "Lucini Italia",
    categoryId: "cat-staples",
    categoryName: "Staples & Pantry",
    description: "Cold-extracted from 100% Italian estate olives within 24 hours of harvest. Notes of green almonds and fresh herbs with peppery finish.",
    specifications: {
      "Volume": "16.9 fl oz (500 ml)",
      "Acidity": "Below 0.3% max at harvest",
      "Certification": "Certified Origin Protected",
    },
    price: 14.99,
    originalPrice: 18.50,
    discountPercent: 19,
    unit: "500 ml glass bottle",
    stock: 42,
    rating: 5.0,
    ratingCount: 310,
    images: [
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80",
    ],
    isFeatured: true,
    tags: ["olive-oil", "evoo", "italian", "gourmet"],
    inStock: true,
  },
  {
    id: "prod-17",
    slug: "organic-quinoa-grain",
    name: "Royal Tri-Color Organic Quinoa",
    brand: "Ancient Harvest",
    categoryId: "cat-staples",
    categoryName: "Staples & Pantry",
    description: "Complete plant protein grain with all 9 essential amino acids. Pre-washed to eliminate bitterness.",
    specifications: {
      "Net Weight": "27 oz (765g)",
      "Origin": "Bolivian Altiplano",
      "Gluten-Free": "Certified GF",
    },
    price: 6.49,
    originalPrice: 7.99,
    discountPercent: 19,
    unit: "27 oz pouch",
    stock: 50,
    rating: 4.7,
    ratingCount: 88,
    images: [
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
    ],
    tags: ["quinoa", "organic", "superfood"],
    inStock: true,
  },

  // Household & Personal Care
  {
    id: "prod-18",
    slug: "plant-based-laundry-detergent",
    name: "Plant-Based Laundry Detergent (Lavender)",
    brand: "Seventh Generation",
    categoryId: "cat-household",
    categoryName: "Household & Personal Care",
    description: "Concentrated enzyme-powered formula fights stubborn stains while staying gentle on delicate sensitive skin.",
    specifications: {
      "Capacity": "90 fl oz (66 loads)",
      "Fragrance": "100% Essential Oils & Botanical Extracts",
      "Cruelty Free": "Leaping Bunny Certified",
    },
    price: 11.99,
    originalPrice: 14.29,
    discountPercent: 16,
    unit: "90 fl oz bottle",
    stock: 35,
    rating: 4.8,
    ratingCount: 175,
    images: [
      "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    tags: ["laundry", "plant-based", "eco-friendly"],
    inStock: true,
  },
  {
    id: "prod-19",
    slug: "bamboo-recycled-paper-towels",
    name: "100% Bamboo Heavy-Duty Paper Towels",
    brand: "Caboo",
    categoryId: "cat-household",
    categoryName: "Household & Personal Care",
    description: "Tree-free paper towels made from fast-growing organic bamboo and sugarcane. Ultra-absorbent 2-ply sheets.",
    specifications: {
      "Pack": "6 Double Rolls (110 sheets/roll)",
      "Biodegradable": "Yes, Chlorine-Free Bleaching",
    },
    price: 9.99,
    originalPrice: 12.99,
    discountPercent: 23,
    unit: "6 Double Rolls",
    stock: 48,
    rating: 4.7,
    ratingCount: 92,
    images: [
      "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=800&auto=format&fit=crop&q=80",
    ],
    isDeal: true,
    tags: ["bamboo", "paper-towel", "tree-free"],
    inStock: true,
  },
  {
    id: "prod-20",
    slug: "cherry-tomatoes-on-vine",
    name: "Campari Sweet Tomatoes on the Vine",
    brand: "Sunset Flavor",
    categoryId: "cat-fruits-veg",
    categoryName: "Fruits & Vegetables",
    description: "Renowned for their sweet flavor and juicy bite. High natural Brix sweetness score, ideal for salads or roasting.",
    specifications: {
      "Net Weight": "16 oz (1 lb)",
      "Vine": "Clustered on vine for maximum freshness",
    },
    price: 3.49,
    originalPrice: 4.29,
    discountPercent: 19,
    unit: "1 lb cluster",
    stock: 50,
    rating: 4.8,
    ratingCount: 165,
    images: [
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80",
    ],
    isPopular: true,
    tags: ["tomatoes", "fresh", "vine-ripened"],
    inStock: true,
  },
];

export const MOCK_REVIEWS = [
  {
    id: "rev-1",
    productId: "prod-1",
    userId: "usr-1",
    userName: "Sarah Jenkins",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "The avocados arrived in absolute pristine condition! Two were ready to eat right away and the others ripened perfectly over the next 2 days. The guacamole was delicious.",
    createdAt: "2026-03-01T10:15:00Z",
  },
  {
    id: "rev-2",
    productId: "prod-1",
    userId: "usr-2",
    userName: "David Chen",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "Cartify's grocery quality is genuinely superior to going to the local supermarket. Fast 15-min delivery too!",
    createdAt: "2026-03-04T14:22:00Z",
  },
  {
    id: "rev-3",
    productId: "prod-6",
    userId: "usr-3",
    userName: "Elena Rostova",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    rating: 5,
    comment: "You can truly taste the difference with pasture-raised eggs. The deep amber yolks make the best scrambled eggs and poached eggs.",
    createdAt: "2026-03-05T09:30:00Z",
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: "coup-1",
    code: "CARTIFY50",
    discountType: "percent",
    discountValue: 15,
    minOrderAmount: 30,
    maxDiscount: 15,
    validUntil: "2026-12-31",
    description: "Get 15% OFF on orders over $30 (max $15)",
  },
  {
    id: "coup-2",
    code: "FRESH20",
    discountType: "fixed",
    discountValue: 10,
    minOrderAmount: 45,
    validUntil: "2026-12-31",
    description: "Save $10 on orders over $45",
  },
  {
    id: "coup-3",
    code: "WELCOME10",
    discountType: "percent",
    discountValue: 10,
    minOrderAmount: 20,
    validUntil: "2026-12-31",
    description: "10% off your first Cartify purchase",
  },
];

export const MOCK_ADDRESSES: Address[] = [
  {
    id: "addr-1",
    userId: "usr-demo",
    fullName: "Alex Rivera",
    mobile: "+1 (555) 234-5678",
    houseFlat: "Apt 4B, Greenfield Residences",
    street: "742 Evergreen Terrace",
    area: "Downtown Metro",
    city: "San Francisco",
    state: "CA",
    pincode: "94107",
    landmark: "Opposite Mission Creek Park",
    addressType: "home",
    isDefault: true,
  },
  {
    id: "addr-2",
    userId: "usr-demo",
    fullName: "Alex Rivera (Tech Hub)",
    mobile: "+1 (555) 987-6543",
    houseFlat: "Suite 500, Innovation Tower",
    street: "100 Market Street",
    area: "Financial District",
    city: "San Francisco",
    state: "CA",
    pincode: "94105",
    landmark: "Near Ferry Building",
    addressType: "work",
    isDefault: false,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-101",
    orderNumber: "CT-89241-XK",
    userId: "usr-demo",
    address: MOCK_ADDRESSES[0],
    items: [
      {
        id: "item-1",
        productId: "prod-1",
        productName: "Organic Hass Avocados",
        productImage: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&auto=format&fit=crop&q=80",
        unitPrice: 4.49,
        quantity: 2,
        totalPrice: 8.98,
        unit: "Pack of 4",
      },
      {
        id: "item-2",
        productId: "prod-6",
        productName: "Pasture-Raised Large Brown Eggs",
        productImage: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=400&auto=format&fit=crop&q=80",
        unitPrice: 5.99,
        quantity: 1,
        totalPrice: 5.99,
        unit: "1 Dozen",
      },
      {
        id: "item-3",
        productId: "prod-8",
        productName: "Artisan Country Sourdough Loaf",
        productImage: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&auto=format&fit=crop&q=80",
        unitPrice: 4.99,
        quantity: 1,
        totalPrice: 4.99,
        unit: "1 Loaf",
      },
    ],
    subtotal: 19.96,
    discount: 2.50,
    deliveryFee: 0,
    tax: 1.45,
    total: 18.91,
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "card",
    paymentTransactionId: "txn_cartify_99214a",
    deliverySlot: "Today, Express 15-Min Delivery",
    estimatedDeliveryTime: "Delivered in 14 mins",
    trackingHistory: [
      {
        status: "order_placed",
        title: "Order Placed",
        description: "Your order was received and confirmed by Cartify Hub",
        timestamp: "2026-03-08T11:02:00Z",
        completed: true,
        current: false,
      },
      {
        status: "confirmed",
        title: "Payment Confirmed",
        description: "Payment verified via Visa ending in 4242",
        timestamp: "2026-03-08T11:03:00Z",
        completed: true,
        current: false,
      },
      {
        status: "preparing",
        title: "Items Picked & Packed",
        description: "Fresh quality items packed in insulated eco-bags",
        timestamp: "2026-03-08T11:08:00Z",
        completed: true,
        current: false,
      },
      {
        status: "out_for_delivery",
        title: "Out for Delivery",
        description: "Rider Marcus on electric scooter is on the way",
        timestamp: "2026-03-08T11:12:00Z",
        completed: true,
        current: false,
      },
      {
        status: "delivered",
        title: "Delivered",
        description: "Order safely handed to Alex at front door",
        timestamp: "2026-03-08T11:16:00Z",
        completed: true,
        current: true,
      },
    ],
    createdAt: "2026-03-08T11:02:00Z",
    updatedAt: "2026-03-08T11:16:00Z",
  },
  {
    id: "ord-102",
    orderNumber: "CT-89312-MN",
    userId: "usr-demo",
    address: MOCK_ADDRESSES[0],
    items: [
      {
        id: "item-4",
        productId: "prod-14",
        productName: "Wild Alaskan Sockeye Salmon Fillet",
        productImage: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400&auto=format&fit=crop&q=80",
        unitPrice: 13.99,
        quantity: 2,
        totalPrice: 27.98,
        unit: "1 lb fillet",
      },
      {
        id: "item-5",
        productId: "prod-16",
        productName: "Single-Estate Extra Virgin Olive Oil",
        productImage: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=80",
        unitPrice: 14.99,
        quantity: 1,
        totalPrice: 14.99,
        unit: "500 ml",
      },
    ],
    subtotal: 42.97,
    discount: 5.00,
    deliveryFee: 0,
    tax: 3.12,
    total: 41.09,
    status: "out_for_delivery",
    paymentStatus: "paid",
    paymentMethod: "upi",
    paymentTransactionId: "upi_ref_882190",
    deliverySlot: "Today, Standard Slot (2:00 PM - 3:00 PM)",
    estimatedDeliveryTime: "Arriving in approx 18 mins",
    trackingHistory: [
      {
        status: "order_placed",
        title: "Order Placed",
        description: "Order received and queued",
        timestamp: "2026-03-09T14:05:00Z",
        completed: true,
        current: false,
      },
      {
        status: "confirmed",
        title: "Payment Confirmed",
        description: "UPI payment received",
        timestamp: "2026-03-09T14:06:00Z",
        completed: true,
        current: false,
      },
      {
        status: "preparing",
        title: "Order Assembled",
        description: "Cold-chain thermal insulation applied",
        timestamp: "2026-03-09T14:15:00Z",
        completed: true,
        current: false,
      },
      {
        status: "out_for_delivery",
        title: "Out for Delivery",
        description: "Courier David is nearby",
        timestamp: "2026-03-09T14:25:00Z",
        completed: true,
        current: true,
      },
      {
        status: "delivered",
        title: "Delivered",
        description: "Estimated delivery in 18 minutes",
        timestamp: "",
        completed: false,
        current: false,
      },
    ],
    createdAt: "2026-03-09T14:05:00Z",
    updatedAt: "2026-03-09T14:25:00Z",
  },
];
